site_name: LHCb_Vilnius_docs
site_url: https://yauhenitalochkan.github.io/LHCb_Vilnius_docs/
nav:
  - Home: index.md
  - Mattermost: mattermost.md
  - ROOT: root.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: deep purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: deep purple

copyright: |
  &copy; 2024 <a href="https://github.com/YauheniTalochkaN"  target="_blank" rel="noopener">Yauheni Talochka</a>, <a href="https://github.com/MindaugasSarpis"  target="_blank" rel="noopener">Mindaugas Sarpis</a>, <a href="https://github.com/Tamsta-273C"  target="_blank" rel="noopener">Oleg Kravcov</a>